server:
  port: ${SERVER_PORT:8081}

spring:
  main:
    allow-bean-definition-overriding: true

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:password@localhost:27017/cycle_db?authSource=admin}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: cycle-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:8085}/realms/period-tracker
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:8085}/realms/period-tracker/protocol/openid-connect/certs