server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    allow-bean-definition-overriding: true

  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/period_tracker_users}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL:http://localhost:8085}/realms/period-tracker
          jwk-set-uri: ${AUTH_SERVER_URL:http://localhost:8085}/realms/period-tracker/protocol/openid-connect/certs

  keycloak:
    server-url: ${KEYCLOAK_URL:http://localhost:8085}
    realm: ${KEYCLOAK_REALM:period-tracker}
    client-id: ${KEYCLOAK_CLIENT_ID:tracker-app}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}